version: '3.7'

services:
  app:
    image: ${ecr_base_url}/${ecr_image}
    init: true
    restart: always
    env_file: ./.env
    {% if cookiecutter.monitoring == 'y' %}
    environment:
     # add this setting to any container that should dump prometheus metrics
      - PROMETHEUS_MULTIPROC_DIR=/prometheus-multiproc-dir
    {% endif %}
    volumes:
      - backend-static:/root/src/static
      - ./media:/root/src/media

      # If another container is using prometheus metrics, it should dump it's metrics to a subdirectory of the host dir,
      # e.g `- ./prometheus-multiproc-dir/other_container:/prometheus-multiproc-dir` - all containers should use
      # separate subdirs
      - ./prometheus-multiproc-dir:/prometheus-multiproc-dir
    {% if cookiecutter.monitoring == 'y' %}
      - ./prometheus-multiproc-dir/app:$${PROMETHEUS_MULTIPROC_DIR}
    {% endif %}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${region}
        awslogs-group: /aws/ec2/${name}-${env}
        tag: '$${INSTANCE_ID_SUBST}-app'
        awslogs-create-group: "true"

  {% if cookiecutter.monitoring == 'y' %}
  node-exporter:
    image: ghcr.io/reef-technologies/node-exporter-aws-ec2:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    logging: &exporter_logging
      driver: journald
      options:
        tag: '{% raw %}{{.Name}}{% endraw %}'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.40.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    logging:
      <<: *exporter_logging
  {% endif %}

  nginx:
    image: 'ghcr.io/reef-technologies/nginx-rt:v1.2.0'
    restart: unless-stopped
    healthcheck:
      test: wget -q --spider http://0.0.0.0/admin/login || exit 1
    depends_on:
      - app
      {% if cookiecutter.monitoring == 'y' %}
      - cadvisor
      - node-exporter
      {% endif %}
    command: nginx -g 'daemon off;'
    ports:
      {% if cookiecutter.monitoring == 'y' %}
      - 10443:10443
      {% endif %}
      - 8000:8000
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/config_helpers:/etc/nginx/config_helpers
      - backend-static:/srv/static:ro
      - ./media:/srv/media:ro
      - ./nginx/monitoring_certs:/etc/monitoring_certs
    logging:
      driver: awslogs
      options:
        awslogs-region: ${region}
        awslogs-group: /aws/ec2/${name}-${env}
        tag: '$${INSTANCE_ID_SUBST}-nginx'
        awslogs-create-group: "true"
    {% if cookiecutter.monitoring == 'y' %}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    {% endif %}

volumes:
  backend-static: